# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f154e4c104fbfd4df1257d1eaa146a17eb37f8043d61ec30a901c4b14cbe73d5b84bf8eb660c5a0b9f900b9256bfdddb1148d527f1d340efea48e55efa0fe972
  GOOGLE_KEY: "98707902639-smshmap3mb98jk6q4v4hjok1sagha983.apps.googleusercontent.com"
  GOOGLE_SECRET: "BlAtuHiHDlLgVSLp6sLGF1fv"
  FB_KEY: "2011898779084637"
  FB_SECRET: "afe5a2bea5489bfb43193a7757cb20c0"
  VK_KEY: "6301776"
  VK_SECRET: "k7DcAGiGIdRiuIOESUE1"
  DEVISE_SECRET: 'de42cd9313a708d77b9931684558cb325e9f316da33bd17d4e68e9188b5ee3cb7a3e950b19164b767bca40d3922c8f731da42086d2d6e31dbb55d9f53548f573'

test:
  secret_key_base: 1953113cc359b08c191b086936482263e9a72c2a2a45883b4e939095b8c513eade2ef58ff81dd59e2f60aa511673470d75cb4120e0df0d9bb27cd25611ccd5d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  GOOGLE_KEY: <%= ENV["GOOGLE_KEY"] %>
  GOOGLE_SECRET: <%= ENV["GOOGLE_SECRET"] %>
  FB_KEY: <%= ENV["FB_KEY"] %>
  FB_SECRET: <%= ENV["FB_SECRET"] %>
  VK_KEY: <%= ENV["VK_KEY"] %>
  VK_SECRET: <%= ENV["VK_SECRET"] %>
  DEVISE_SECRET: <%= ENV["DEVISE_SECRET"] %>
